### ISSUE TITLE
Labels overlap because of active/hover states

### ISSUE THREAD

**Issue by CREEATION** [febLey/febley.github.io#1]
Maybe make it so that only one label can be shown at a time?
//e: that only one icon/label can be active, is what I'm thinking.

![febli](https://user-images.githubusercontent.com/3277769/48076093-ccd36800-e1e4-11e8-88b0-d50e9c6886d8.png)
(left: `active`, right: `hover`)

**Comment by febLey** [comment]
Kind of fixed in https://github.com/febLey/febley.github.io/commit/39c267e4c89cc5e7d49588cacef44021c8582be9
That's the most effort I'm willing to put in.

**Comment by CREEATION** [comment]
Alrighty, but you should remove ":focus" then, too (tabbing through links). 🐢 
Didn't think about "focus" when I made the issue.
